In [2]:
import array as arr

# Create array with 5 integers
array_int = arr.array('i', [1, 3, 5, 7, 9])

# Create array with 5 float
array_float= arr.array('f', [1.1, 3.3, 5.5, 7.7, 9.9])

# Append two more integers
array_int.append(11)
array_int.append(13)

# Append one more float
array_float.append(11.11)

# Print both array
print(array_int)
print(array_float)


array('i', [1, 3, 5, 7, 9, 11, 13])
array('f', [1.100000023841858, 3.299999952316284, 5.5, 7.699999809265137, 9.899999618530273, 11.109999656677246])


2. Given a random set of numbers, print them in sorted order.
A1[] = {5,97,23,45,2,63,2,14}

In [11]:
# Let A1 be a set of random numbers, e.g. as given in question {5,97,23,45,2,63,2,14}
A1 = {5,97,23,45,2,63,2,14}

# Print the random set of numbers in sorted order
print(sorted(A1))

[2, 5, 14, 23, 45, 63, 97]





```
3. Given array is A2= [1,5,3,6,43,24,2,76,17].
Print:
      a. All elements between index 2 and 6.
      b. All elements after index 3.
      c. First 2 elements of the list
      d. Elements present at even indices (ie. index 0,2,4…)
```



In [52]:
# Given array
A2 = [1, 5, 3, 6, 43, 24, 2, 76, 17]

# Print all elements between index 2 and 6
print('Between index 2 and 6', A2[3:7])

# Print all elements after index 3
print('After index 3: ', A2[4:])

# Print first 2 elements of the list
print('First 2 elements: ', A2[0:2])

# Print elements present at even indices (ie. index 0,2,4…)
print('Elements at even indices: ', A2[0::2])

Between index 2 and 6 [6, 43, 24, 2]
After index 3:  [43, 24, 2, 76, 17]
First 2 elements:  [1, 5]
Elements at even indices:  [1, 3, 43, 2, 17]


4. Given an array A of size 6 of integers. Your task is to find the minimum and
maximum elements in the array.
A3={3,1,9,137, 1023,54}


In [20]:
A3 = {3, 1, 9, 137, 1023, 54}
print('Minimum element is : ', min(A3))
print('Maximum element is : ', max(A3))


Minimum element is :  1
Maximum element is :  1023


5. Find all the elements occurring more than once in the given array. Arr [] = {1,8,3,1,4,8,5}


In [28]:
Arr = [1,8,3,1,4,8,5]

# Find all repeating elements and store them in repeating_ele set
repeating_ele = {ele for ele in Arr if Arr.count(ele) > 1}

# Print the repeating elements
print('Repeating elements are ', repeating_ele)


Repeating elements are  {8, 1}


6. Write a Python program to find those numbers which are divisible by 8 and multiple of 5,
between 1000 and 3400 (both included).


In [40]:
print(1000%40)

0


In [42]:
# Numbers divisible by and 8 and multiple of 5 must be multiples of 40
# Since 1000 is divisible by 40, we can start loop from 1000 and keep increamenting it by 40 till 3400
for num in range(1000, 3400, 40):
  print(num)

1000
1040
1080
1120
1160
1200
1240
1280
1320
1360
1400
1440
1480
1520
1560
1600
1640
1680
1720
1760
1800
1840
1880
1920
1960
2000
2040
2080
2120
2160
2200
2240
2280
2320
2360
2400
2440
2480
2520
2560
2600
2640
2680
2720
2760
2800
2840
2880
2920
2960
3000
3040
3080
3120
3160
3200
3240
3280
3320
3360


7. Write a Python program to get the Fibonacci series between 0 to 50.

In [50]:
feb_no = []
num = 1
sum = 0
while sum <= 50:
  print(sum)
  sum = sum + num
  num = num + 1




0
1
3
6
10
15
21
28
36
45


8. Matrix multiplication in python. Mupltiply give two matrices and print the resultant
matrix.
A = [[2,3,4],[1,4,2].[1,4,3]] B =[[2,5,1],[1,1,1],[6,5,2]]

In [57]:
import numpy as np

A = np.array([[2, 3, 4], [1, 4, 2], [1, 4, 3]])
print('Metrix A = \n', A, '\n')

B = np.array([[2, 5, 1], [1, 1, 1], [6, 5, 2]])
print('Matrix B = \n', B, '\n')

print('Dot product (Matrix mutliplication result) = \n', A.dot(B))

Metrix A = 
 [[2 3 4]
 [1 4 2]
 [1 4 3]] 

Matrix B = 
 [[2 5 1]
 [1 1 1]
 [6 5 2]] 

Dot product (Matrix mutliplication result) = 
 [[31 33 13]
 [18 19  9]
 [24 24 11]]


9. Create two directories and merge them

In [59]:
# Create first dictionary dict_a
dict_a = {'ak1': 11, 'ak2': 12, 'ak3': 13}
print('First dictionary: ', dict_a)

# Create second dictionary dict_b
dict_b = {'bk1': 21, 'bk2': 22, 'bk3': 23}
print('Second dictionary: ', dict_b)

# Merge the two dictionries
dict_merged = dict_a | dict_b

#print merged dictionaries
print('Merged dictionary: ', dict_merged)



First dictionary:  {'ak1': 11, 'ak2': 12, 'ak3': 13}
Second dictionary:  {'bk1': 21, 'bk2': 22, 'bk3': 23}
Merged dictionary:  {'ak1': 11, 'ak2': 12, 'ak3': 13, 'bk1': 21, 'bk2': 22, 'bk3': 23}


10. Create a string s= “1576” and parse it into an integer number.

In [1]:
s = '1576'
print('s value: ', s, 'type: ', type(s))
int_s = int(s)
print('int_s value: ', int_s, 'type: ', type(int_s))

s value:  1576 type:  <class 'str'>
int_s value:  1576 type:  <class 'int'>
